// Autogenerated file, please don't edit
// style_dictionary.dart
//

import 'package:flutter/material.dart';

class StyleDictionary {
    static const darkblue = Color(0xFF151551);
    static const indigo = Color(0xFF312680);
    static const purple = Color(0xFF6025B5);
    static const yellow = Color(0xFFE7C534);
    static const grey = Color(0xFF788FB4);
    static const fontColorOnLight = Color(0xFF1E2023);
    static const fontColorOnDark = Color(0xFFF1F5FB);
    static const lightYellow = Color(0xFFF2E3A0);
    static const disabledYellow = Color(0xFFE1DFD3);
    static const mustard = Color(0xFFBE9E14);
    static const white = Color(0xFFFFFFFF);
    static const lightGrey = Color(0xFFD9D9D9);
    static const inter = 'Inter';
    static const normal = FontWeight.normal;
    static const semibold = FontWeight.w600;
    static const headline = TextStyle(fontFamily: 'Inter',fontSize: 20,);
    static const headlineSemiBold = TextStyle(fontFamily: 'Inter',fontSize: 20,);
    static const body = TextStyle(fontFamily: 'Inter',fontSize: 16,);
    static const body2 = TextStyle(fontFamily: 'Inter',fontSize: 14,);
    static const headline40 = TextStyle(fontFamily: 'Inter',fontSize: 40,);
}
